// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	infos "cpw/go-zero-demo/internal/handler/infos"
	"cpw/go-zero-demo/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/infos/list",
				Handler: infos.ListInfosHandler(serverCtx),
			},
		},
	)
}
